### ISSUE TITLE
Project crashes when I attempt to open

### ISSUE THREAD

**Issue by johnss518** [learn-co-curriculum/objc-parrot#6]
Crashed Thread:        19

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
ProductBuildVersion: 7A1001
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-8186/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/TargetSnapshots/XCBuildFileRefDGSnapshot.m:474
Details:  Cannot call addBuildFileRef: when file refs are frozen
Object:   <XCBuildFileRefArrayDGSnapshot: 0x7fe10574dff0>
Method:   -addBuildFileRef:
Thread:   <NSThread: 0x7fe104da7ac0>{number = 10, name = (null)}
Hints:   None
Backtrace:
  0  0x000000011081f904 -[IDEAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:](in IDEKit)
  1  0x000000010f3ea22e _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010f3ea445 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x00000001174e1225 -[XCBuildFileRefArrayDGSnapshot addBuildFileRef:](in DevToolsCore)
  4  0x00000001174bdbef -[XCBuildPhaseDGSnapshot(DependencyGraphCreation) groupDependencyNode:ifNecessaryForLaterProcessingWithMacroExpansionScope:](in DevToolsCore)
  5  0x00000001174d1df4 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) _processOutputNodes:forRegionVariantName:processedPaths:originalBuildRule:withMacroExpansionScope:](in DevToolsCore)
  6  0x00000001174d05f7 -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) _computeDependenciesForBuildFileReference:usingBuildRule:withMacroExpansionScope:processedPaths:](in DevToolsCore)
  7  0x00000001174d2aae -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForBuildFileReference:usingBuildRule:withMacroExpansionScope:](in DevToolsCore)
  8  0x00000001174d2f5b -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForBuildFileReference:withMacroExpansionScope:](in DevToolsCore)
  9  0x00000001174be624 -[XCBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesWithMacroExpansionScope:](in DevToolsCore)
 10  0x00000001174d5b3f -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesForAllBuildFileReferencesWithMacroExpansionScope:](in DevToolsCore)
 11  0x00000001174d6f1d -[XCSourcesBuildPhaseDGSnapshot(DependencyGraphCreation) computeDependenciesWithMacroExpansionScope:](in DevToolsCore)
 12  0x000000011740d645 -[XCProductTypeSpecification computeDependenciesWithMacroExpansionScope:](in DevToolsCore)
 13  0x00000001174b6f90 -[XCNativeTargetDGSnapshot(DependencyGraphCreation) computeDependenciesWithMacroExpansionScope:](in DevToolsCore)
 14  0x000000011738a3e5 -[PBXTargetBuildContext createDependencyGraphWithTargetDGSnapshot:](in DevToolsCore)
 15  0x00000001173a6607 -[PBXTargetBuildContext(DependencyGraphEvents) dg_setTargetSnapshot:](in DevToolsCore)
 16  0x00000001173a5ccc -[PBXTargetBuildContext(DependencyGraphEvents) processDependencyGraphEvents](in DevToolsCore)
 17  0x00000001174052d2 -[XCBlockQueue _processNextBlockInThreadSlotNumber:](in DevToolsCore)
 18  0x0000000117405554 -[XCBlockQueue _processBlocksInThreadSlotNumber:](in DevToolsCore)
 19  0x00007fff95cfb084 __NSThread__start__ (in Foundation)
 20  0x00007fff958879b1 _pthread_body (in libsystem_pthread.dylib)
 21  0x00007fff9588792e _pthread_body (in libsystem_pthread.dylib)
 22  0x00007fff95885385 thread_start (in libsystem_pthread.dylib)

abort() called

Application Specific Signatures:
0

Global Trace Buffer (reverse chronological seconds):
3.121192     CFNetwork                  0x00007fff8a55c3b4 NSURLConnection finished with error - code -1100
3.227329     CFNetwork                  0x00007fff8a49d07b TCP Conn 0x7fe10512b180 SSL Handshake DONE
3.248505     CFNetwork                  0x00007fff8a49d07b TCP Conn 0x7fe10512bf20 SSL Handshake DONE
3.341252     CFNetwork                  0x00007fff8a49cf57 TCP Conn 0x7fe10512b180 starting SSL negotiation
3.341332     CFNetwork                  0x00007fff8a49b927 TCP Conn 0x7fe10512b180 complete. fd: 43, err: 0
3.343519     CFNetwork                  0x00007fff8a52a121 TCP Conn 0x7fe10512b180 event 1. err: 0
3.897068     CFNetwork                  0x00007fff8a49cf57 TCP Conn 0x7fe10512bf20 starting SSL negotiation
3.897198     CFNetwork                  0x00007fff8a49b927 TCP Conn 0x7fe10512bf20 complete. fd: 44, err: 0
3.897497     CFNetwork                  0x00007fff8a52a121 TCP Conn 0x7fe10512bf20 event 1. err: 0

**Comment by markedwardmurray** [comment]
learn-co-students batch repo doesn't have the commits that fix the lab for Xcode 7.

**Comment by markedwardmurray** [comment]
forgot to close this, we solved this problem with Xcode 7.0 for all the iOS labs in the curriculum. Thanks, johnss518 for reporting your problem.
