### ISSUE TITLE
Issue with pull request

### ISSUE THREAD

**Issue by Dewalk** [learn-co-curriculum/objc-parrot#8]
For some reason, my pull request for this lesson does not seem to be registering in the Learn.co interface. Github says that I've created a pull request, but the green button in Learn.co is not lit, so I can't move on from this lesson although I've completed it and the updated files are on github.

Please help!!!!

Thanks,

Dawn

**Comment by markedwardmurray** [comment]
Hi Dawn, it looks like you forked the curriculum repository not the student copy. You'll need to find the correct repository on the `learn-co-students` (vs `learn-co-curriculum`) GitHub organization for the website to register your solution. If you're in the ios-prework batch then the repo you'll need to clone and solve is: https://github.com/learn-co-students/objc-parrot-001-prework-ios

Of course if you've already solved the lab, just copy/paste your progress into the new clone and go from there.

**Comment by Dewalk** [comment]
Thank you Mark for your reply.
I will retry and make sure I fork the correct repository.

Thank you for your help,

Dawn Walker

**Comment by Dewalk** [comment]
HI Mark,

Upon further review, it looks to me as if I have forked the
learn-co-students repository. I've done 3 different commits and after
redoing the lesson again tonight, I got a message that everything was up to
date. I've attached my terminal output and a screen shot for your review.
Is there a way to delete the 3 previous commits for this lesson and start
fresh? Even after removing the old objc-parrot-001-prework-ios directory
from my directory and cloning it again, it still held all of my code from
previous even though the time stamp on my computer shows the
directory/files were created again tonight.

Thank you,

Dawn Walker

**Comment by markedwardmurray** [comment]
Yes, you did fork the correct repository after all. I'm sorry I didn't look closely over the weekend, I had thought you had cloned the wrong repository here, so recloning from the correct repo as you did the first time will bring down your previous work as it did. I found your fork, though, and it seems like your solution posted online should be satisfactory. I just closed and reopened your pull request to see if that will reque Learn.co's webhook to listen for the pull request. If your progress still doesn't show on your profile then try the "manual override" feature to keep moving forward. The "next lesson" should still be enabled and allow you to move on despite not having all the green lights.

**Comment by Dewalk** [comment]
Hi Mark,

Yes, thank you. That seems to have done it. The lesson now indicates that
the pull request was opened and the green light is on. My lesson is
complete.

Thank you for your assistance,

Dawn Walker

**Comment by markedwardmurray** [comment]
Awesome 🎩

On Feb 9, 2016, at 12:46, Dewalk notifications@github.com wrote:

Hi Mark,

Yes, thank you. That seems to have done it. The lesson now indicates that
the pull request was opened and the green light is on. My lesson is
complete.

Thank you for your assistance,

Dawn Walker
